export enum LOG_TYPES {
  CHAT = "chat",
  CHAT_CACHED = "chat-cached",
  NO_RESPONSE = "no-response",
  BILLING = "BILLING",
  TECHNICAL = "TECHNICAL",
  PRODUCT_FEEDBACK = "PRODUCT FEEDBACK",
  GENERAL_QUESTION = "GENERAL QUESTION",
  REFUND = "REFUND",
  ESCALATE = "ESCALATE",
}
